language: c
script: asdf plugin-test bazel https://github.com/mrinalwadhwa/asdf-bazel.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
